backend/cmd/headlamp: Fix issue in cluster looking for kube config
kubernetes-sigs/headlamp pull request #2323
Opened 2024-09-11 13:09 UTC by illume

Fixes #1826

2024-09-16 13:55 UTC, joaquimrocha requested changes
Left a comment in the 1st patch that then I realize you had already implemented in the 2nd patch.
I think the 2nd patch is the right approach. Let's keep the possibility of mixing loading clusters from different places, but I don't think we need the new todo comments.

2024-09-16 13:55 UTC, joaquimrocha commented on backend/cmd/headlamp.go
> +	if !config.useInCluster {
Many users have asked how they could add more clusters when headlamp is running in a cluster. I find the mixed use-case a bit cornerish, but don't see a reason why we should restrict mixing loading kubeconfigs with in-cluster. So maybe what we need to do is not log issues about loading kubeconfigs if we are running in-cluster.

2024-09-16 13:55 UTC, joaquimrocha commented on backend/cmd/headlamp.go
> +			logger.Log(logger.LevelInfo, nil, err, "loading kubeconfig")
maybe we could define the log into a variable and then only have one logger.Log call? I guess the code would be more easily understood.

2024-09-16 14:34 UTC, illume commented
There's a bit more discussion since in this issue:
> There is a use case of using kube config in cluster here: https://github.com/headlamp-k8s/headlamp/issues/1826#issuecomment-2343595252

2024-09-19 13:20 UTC, joaquimrocha commented
> There's a bit more discussion since in this issue:
> 
> > There is a use case of using kube config in cluster here: [#1826 (comment)](https://github.com/headlamp-k8s/headlamp/issues/1826#issuecomment-2343595252)

Either way, I think we need to keep supporting this. By default we don't look for a kubeconfig if `-in-cluster` is passed, so I don't see an inconvenient with keeping support for this "misfeature".
In terms of making it work, just not aborting if `-in-cluster` is also used should be sufficient.

2025-07-10 12:11 UTC, joaquimrocha commented
Maybe @skoeva can revamp this if it's still valid.

2025-09-08 12:47 UTC, closed without merging