Fix AlertNotification
kubernetes-sigs/headlamp pull request #2571
Opened 2024-11-14 12:48 UTC by callmevladik

## Describe the bug
AlertNotification has "Try again" button which doesn't do anything, the potential reason could be that some of the dependencies in useEffect are not updated or badly composed registerSetInterval function.

## To Reproduce
Steps to reproduce the bug:
1. Go to any page with possible AlertNotification
2. Mock error behaviour
3. Click try again button, so that immediately after clicking the "healthz" request will be triggered instantly and AlertNotification must disappear.

2024-11-14 20:39 UTC, skoeva commented
Hi, thanks for opening this PR! Regarding the issue here, it would be best to log it in the repo [here](https://github.com/headlamp-k8s/headlamp/issues/new/choose)

![image](https://github.com/user-attachments/assets/3ba80313-a84e-46a5-80e8-b294f2567ed0)

And then you can link the issue to this PR and avoid having a super long PR description. This should generally be reserved for a short description of the changes, along with any helpful instructions to test the changes for anyone reviewing. 

Feel free to reference our [contribution guidelines](https://headlamp.dev/docs/latest/contributing/) and reach out if you have any questions :)

2024-11-18 16:13 UTC, illume commented
Hi @callmevladik 

thanks for this fix! Appreciate it.

A few notes about the CI build errors:
- The DCO check can be fixed by adding a sign off with `git commit --amend -s`
- The test plugins failure looks to be unrelated to this PR (Please ignore, it will be fixed in another PR)
- The frontend test failure is because of i18n. Please run `make frontend-i18n-check` from repo root to check it. I think if you added any translations you can run `npm run i18n` from within frontend/ which will generate empty translations for the other locales.

2024-11-18 16:15 UTC, illume requested changes
I left a previous comment about how to address the CI job failures.

2025-01-16 10:40 UTC, joaquimrocha commented
Hi @callmevladik . Are you able to follow up on the PR's comments?
Let us know if you prefer us to address the suggested changes.

2025-04-25 14:13 UTC, illume commented
@callmevladik hey hey. We moved into the Kubernetes org recently where they require signing CLA instead of DCO.

ps. Our offer to rebase things and fix the CI jobs stands. Let us know?

2025-07-08 12:13 UTC, skoeva reviewed
Closing this for now, feel free to open if you choose to continue progress

2025-07-08 12:13 UTC, closed without merging