frontend: PluginSettings: Refactor local storage and plugin data
kubernetes-sigs/headlamp pull request #2671
Opened 2024-12-12 00:39 UTC by vyncent-t

2024-12-12 01:04 UTC, vyncent-t commented
Last push adds backwards comp so that all settings wont be set to off or on

2024-12-12 01:11 UTC, vyncent-t commented
I have tried to keep the changes as small as possible to accomplish everything it needs to, I am not using the map object to save information anymore, although to hit these targets I still had to use most of what I had reworked previously

@joaquimrocha @sniok 

for this PR the targets it needs to hit were:
- not have the plugins version/data coming from a client-side stored version of it

The plugin data comes from the backend, reused the same method of reaching it from the previous rework

- avoid having to store all that data when what we are interested in is checking whether the plugins are enabled on the user's side

The data is now trimmed down to just being the name and isEnabled, it is now being used the same way as the original settings where this local saved item is how new app start ups save plugin settings

- need to be backwards compatible with the previous settings method

The local storage handling logic checks for the old format and changes it to the new format

2024-12-19 16:14 UTC, sniok commented
Some things to do to avoid duplicating of logic:

 - refactor fetching logic into a single place that both PluginSettings and fetchAndExecutePlugins use
 - use react-query for fetching to have caching and avoid refetching the same stuff

2025-02-06 15:13 UTC, vyncent-t commented
pushing rebase of current main

2025-02-07 13:00 UTC, sniok commented on e2e-tests/tests/pluginSetting.spec.ts
> +// to do: fix this or remove this test all together to make compatiable with new plugin name print format (not including @kinvolk in name)
could you try to modify this test so it passes (in CI) on this branch?

2025-02-07 13:01 UTC, sniok commented on frontend/src/lib/k8s/api/v2/plugins.ts
> +          {
curly brackets are not needed here

2025-02-07 13:04 UTC, sniok commented on frontend/src/lib/k8s/api/v2/plugins.ts
> +      const compatibleVersion = '>=0.8.0-alpha.3';
this constant is repeated in 'fetchAndExecutePlugins' function. you could reuse this function there to avoid duplication

2025-02-07 13:06 UTC, sniok commented on frontend/src/plugin/index.ts
> +    backendPlugins.map(p => p.name) !== settingsPlugins.map(p => p.name);
you can't compare arrays like that, this will always be false because they are compared by reference and not by their content

2025-02-07 13:06 UTC, sniok requested changes
thanks for the update, left a couple of comments

2025-02-12 17:22 UTC, vyncent-t commented on frontend/src/plugin/index.ts
> +    backendPlugins.map(p => p.name) !== settingsPlugins.map(p => p.name);
done!

2025-02-12 17:22 UTC, vyncent-t commented on frontend/src/lib/k8s/api/v2/plugins.ts
> +      const compatibleVersion = '>=0.8.0-alpha.3';
done!

2025-02-12 17:22 UTC, vyncent-t commented on frontend/src/lib/k8s/api/v2/plugins.ts
> +      fetch(`${helpers.getAppUrl()}${path}/package.json`).then(resp => {
done!

2025-02-12 17:22 UTC, vyncent-t commented on frontend/src/lib/k8s/api/v2/plugins.ts
> +          {
done!

2025-02-13 15:42 UTC, sniok requested changes
Plugins setting stopped working, check the pod-counter plugin settings

2025-02-28 13:54 UTC, illume commented
@vyncent-t It seems there’s conflicts now. Can you please fix them?

2025-04-16 12:02 UTC, closed without merging

2025-04-16 12:02 UTC, illume commented
Closing because new PR is here: https://github.com/kubernetes-sigs/headlamp/pull/3123